const map=L.map('map',{worldCopyJump:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
const state={objects:[],settings:{ai_images:true},globe_label:''};let results=document.getElementById('results');let drag=null;
const $=id=>document.getElementById(id);
function centerOf(g){let pts=[];function walk(x){if(typeof x[0]==='number')pts.push(x);else x.forEach(walk)}walk(g.coordinates);let lon=pts.reduce((s,p)=>s+p[0],0)/pts.length,lat=pts.reduce((s,p)=>s+p[1],0)/pts.length;return[lat,lon]}
function transform(g,from,to){const a=from[0]*Math.PI/180,b=to[0]*Math.PI/180,ca=Math.cos(a),cb=Math.max(.05,Math.cos(b));function p(x){if(typeof x[0]==='number'){const east=(x[0]-from[1])*ca;const north=x[1]-from[0];return[to[1]+east/ cb,to[0]+north]}return x.map(p)}return {...g,coordinates:p(g.coordinates)} }
function renderObject(o){if(o.layer)map.removeLayer(o.layer);o.layer=L.geoJSON(o.geojson,{style:{color:'#ffffff',weight:2,fillOpacity:.22,fillColor:'#3b82f6'}}).addTo(map);o.layer.eachLayer(l=>{l.on('mousedown',e=>{drag={o,start:[e.latlng.lat,e.latlng.lng],center:centerOf(o.geojson),mapStart:o.geojson};L.DomEvent.stopPropagation(e)});l.on('click',()=>showPopup(o,l))});}
map.on('mousemove',e=>{if(!drag)return;const o=drag.o;o.geojson=transform(drag.mapStart,drag.center,[e.latlng.lat,e.latlng.lng]);renderObject(o)});map.on('mouseup',()=>{if(drag){drag=null;save()}});
function flagUrl(o){const cc=o.address?.country_code;return cc?`https://flagcdn.com/w320/${cc}.png`:null}
async function showPopup(o,l){const image=o.image?`<img src="${o.image}">`:'';l.bindPopup(`<b>${o.name}</b><br>${o.display_name||''}${image}`).openPopup()}
function renderList(){const box=$('objects');box.innerHTML='';state.objects.forEach((o,i)=>{const d=document.createElement('div');d.className='obj';d.innerHTML=`<div class="objTop"><strong>${o.name}</strong><button data-i="${i}">Удалить</button></div>${o.image?`<img src="${o.image}">`:''}`;d.querySelector('button').onclick=()=>{if(o.layer)map.removeLayer(o.layer);state.objects.splice(i,1);renderList();save()};box.appendChild(d)})}
async function addResult(r){const o={...r,geojson:structuredClone(r.geojson),original_center:centerOf(r.geojson),image:null};state.objects.push(o);renderObject(o);renderList();map.fitBounds(o.layer.getBounds(),{padding:[40,40],maxZoom:6});save();if($('aiImages').checked){try{const p=await fetch('/api/groq-prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:o.name})}).then(x=>x.json());const im=await fetch('/api/generate-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p.prompt})}).then(x=>x.json());o.image=im.image;renderList();save()}catch(e){console.warn(e)}}}
async function doSearch(){const q=$('search').value.trim();if(!q)return;results.innerHTML='Поиск…';try{const arr=await fetch('/api/search?q='+encodeURIComponent(q)).then(r=>r.json());results.innerHTML='';arr.forEach(r=>{const d=document.createElement('div');d.className='result';d.textContent=r.display_name;d.onclick=()=>{results.innerHTML='';$('search').value=r.name;addResult(r)};results.appendChild(d)})}catch(e){results.textContent='Ошибка поиска'}}
$('searchBtn').onclick=doSearch;$('search').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});$('settingsBtn').onclick=()=>$('settings').classList.toggle('open');$('aiImages').onchange=()=>{state.settings.ai_images=$('aiImages').checked;save()};$('clearBtn').onclick=()=>{state.objects.forEach(o=>o.layer&&map.removeLayer(o.layer));state.objects=[];renderList();save()};$('globeBtn').onclick=()=>{state.globe_label=$('globeInput').value.trim();$('globeLabel').textContent=state.globe_label;save()};
async function save(){fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({objects:state.objects.map(o=>({...o,layer:undefined})),settings:state.settings,globe_label:state.globe_label})}).catch(()=>{})}
async function load(){try{const s=await fetch('/api/state').then(r=>r.json());Object.assign(state,s);$('aiImages').checked=state.settings?.ai_images!==false;$('globeLabel').textContent=state.globe_label||'';state.objects.forEach(renderObject);renderList()}catch(e){console.warn(e)}}load();
